### ISSUE TITLE
exiting this container with exit code 1

### ISSUE THREAD

**Issue by tulasirm** [ludeknovy/jtl-reporter-be#46]
$ docker inspect 5781995dc20d
[
    {
        "Id": "5781995dc20d0c0261c4e54f4aad512997320a20313df26e3f98c82b4de07a33",
        "Created": "2020-06-11T03:22:49.886766229Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "npm",
            "run",
            "migrate",
            "up"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2020-06-11T03:27:11.776709814Z",
            "FinishedAt": "2020-06-11T03:27:17.783204896Z"
        },
        "Image": "sha256:931fe223a057374ef501b5b8d8b64e02a44f0a17309535dcb7b5ae30e7b5b1a9",
        "ResolvConfPath": "/var/lib/docker/containers/5781995dc20d0c0261c4e54f4aad512997320a20313df26e3f98c82b4de07a33/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/5781995dc20d0c0261c4e54f4aad512997320a20313df26e3f98c82b4de07a33/hostname",
        "HostsPath": "/var/lib/docker/containers/5781995dc20d0c0261c4e54f4aad512997320a20313df26e3f98c82b4de07a33/hosts",
        "LogPath": "/var/lib/docker/containers/5781995dc20d0c0261c4e54f4aad512997320a20313df26e3f98c82b4de07a33/5781995dc20d0c0261c4e54f4aad512997320a20313df26e3f98c82b4de07a33-json.log",
        "Name": "/jtl-reporter_migration_1",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "jtl-reporter_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "DeviceId": "3880",
                "DeviceName": "docker-202:2-75680321-ae8d20476ef5146cc2b15313728f3c4b007290656ac93511a17a6a779226f7c3",
                "DeviceSize": "10737418240"
            },
            "Name": "devicemapper"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "5781995dc20d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DATABASE_URL=postgres://postgres@db/jtl_report",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=12.13.1",
                "YARN_VERSION=1.19.1"
            ],
            "Cmd": [
                "npm",
                "run",
                "migrate",
                "up"
            ],
            "Image": "novyl/jtl-reporter-be:latest",
            "Volumes": null,
            "WorkingDir": "/src/be",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "092823b0b0a9c39c0c49298f1c7e73202fde5e99bfdf0e857d32532366eaa540",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "jtl-reporter",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/thulasiramaiah.sirip/perf-tools/jtl-reporter",
                "com.docker.compose.service": "migration",
                "com.docker.compose.version": "1.25.4"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "32ec131dff126f2216535524ed4c481c208dd1236ee82d4f2dc9d28e2040f585",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/32ec131dff12",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "jtl-reporter_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "5781995dc20d",
                        "migration"
                    ],
                    "NetworkID": "b89dbb2baca954ac333a09b2636976aa00b0a1af73f524eedb8a2314b9011d78",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]

**Comment by ludeknovy** [comment]
Hello @tulasirm 
whats the docker-compose logs output?

**Comment by ludeknovy** [comment]
I found the problem - there is missing
` environment:
      - POSTGRES_HOST_AUTH_METHOD=trust`
in docker-compose file.

**Comment by ludeknovy** [comment]
It should be fixed in: https://github.com/ludeknovy/jtl-reporter/blob/master/docker-compose.yml

thanks for raising this issue up.

**Comment by tulasirm** [comment]
Great! thank you for your quick response, let me check.

Thanks
Thulasi
